language: node_js
node_js:
  - 6.1.0

before_install:
- git config user.name 'WEB-EGG bot'
- git config user.email webegg-bot@blog.leko.jp
- rvm install 2.3.1

install:
- bundle install
- npm install
- npm install netlify-cli -g

script:
- bundle exec middleman build
- npm run lint

deploy:
  - provider: script
    script: netlify deploy -e production
    on:
      branch: master
  - provider: script
    script: netlify deploy -e deploy-preview
    on:
      condition: $TRAVIS_BRANCH != 'master'
