// flow-typed signature: 9e4884acb87b21eb419bd940b2738fbc
// flow-typed version: <<STUB>>/almin-logger_v^4.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'almin-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'almin-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'almin-logger/lib/AlminLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/lib/AsyncLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/lib/log/LogChunk' {
  declare module.exports: any;
}

declare module 'almin-logger/lib/log/LogGroup' {
  declare module.exports: any;
}

declare module 'almin-logger/lib/log/PrintLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/lib/performance-now' {
  declare module.exports: any;
}

declare module 'almin-logger/lib/SyncLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/src/AlminLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/src/AsyncLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/src/log/LogChunk' {
  declare module.exports: any;
}

declare module 'almin-logger/src/log/LogGroup' {
  declare module.exports: any;
}

declare module 'almin-logger/src/log/PrintLogger' {
  declare module.exports: any;
}

declare module 'almin-logger/src/SyncLogger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'almin-logger/lib/AlminLogger.js' {
  declare module.exports: $Exports<'almin-logger/lib/AlminLogger'>;
}
declare module 'almin-logger/lib/AsyncLogger.js' {
  declare module.exports: $Exports<'almin-logger/lib/AsyncLogger'>;
}
declare module 'almin-logger/lib/log/LogChunk.js' {
  declare module.exports: $Exports<'almin-logger/lib/log/LogChunk'>;
}
declare module 'almin-logger/lib/log/LogGroup.js' {
  declare module.exports: $Exports<'almin-logger/lib/log/LogGroup'>;
}
declare module 'almin-logger/lib/log/PrintLogger.js' {
  declare module.exports: $Exports<'almin-logger/lib/log/PrintLogger'>;
}
declare module 'almin-logger/lib/performance-now.js' {
  declare module.exports: $Exports<'almin-logger/lib/performance-now'>;
}
declare module 'almin-logger/lib/SyncLogger.js' {
  declare module.exports: $Exports<'almin-logger/lib/SyncLogger'>;
}
declare module 'almin-logger/src/AlminLogger.js' {
  declare module.exports: $Exports<'almin-logger/src/AlminLogger'>;
}
declare module 'almin-logger/src/AsyncLogger.js' {
  declare module.exports: $Exports<'almin-logger/src/AsyncLogger'>;
}
declare module 'almin-logger/src/log/LogChunk.js' {
  declare module.exports: $Exports<'almin-logger/src/log/LogChunk'>;
}
declare module 'almin-logger/src/log/LogGroup.js' {
  declare module.exports: $Exports<'almin-logger/src/log/LogGroup'>;
}
declare module 'almin-logger/src/log/PrintLogger.js' {
  declare module.exports: $Exports<'almin-logger/src/log/PrintLogger'>;
}
declare module 'almin-logger/src/SyncLogger.js' {
  declare module.exports: $Exports<'almin-logger/src/SyncLogger'>;
}
