// flow-typed signature: 01b4d5723623451f24fe14ab65db217b
// flow-typed version: <<STUB>>/shallow-equal-object_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shallow-equal-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shallow-equal-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shallow-equal-object/lib/src/shallow-equal-object' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shallow-equal-object/lib/src/shallow-equal-object.js' {
  declare module.exports: $Exports<'shallow-equal-object/lib/src/shallow-equal-object'>;
}
