name: CI
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['14.15.x']
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: npm run lint
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['14.15.x']
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: npm run test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
